<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-DO4RSNU" failures="1" tests="1" name="TDC AUTOMATION TEST(failed)" time="10.127" errors="0" timestamp="15 Nov 2022 04:21:14 GMT">
  <testcase classname="com.tdc.lms.testcases.LoginPageTest" name="invalidEmail" time="4.202">
    <failure type="java.lang.AssertionError" message="expected [There is no user record corresponding to this identifier.The user may have been deleted. (auth/user-not-found).] but found [There is no user record corresponding to this identifier. The user may have been deleted. (auth/user-not-found).]">
      <![CDATA[java.lang.AssertionError: expected [There is no user record corresponding to this identifier.The user may have been deleted. (auth/user-not-found).] but found [There is no user record corresponding to this identifier. The user may have been deleted. (auth/user-not-found).]
at com.tdc.lms.testcases.LoginPageTest.invalidEmail(LoginPageTest.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- invalidEmail -->
  <testcase classname="com.tdc.lms.testcases.LoginPageTest" name="login" time="0.0">
    <ignored/>
  </testcase> <!-- login -->
</testsuite> <!-- TDC AUTOMATION TEST(failed) -->
